### ISSUE TITLE
Hello,I can't find the "epoch_5.pt" file,can you give me a file?thanks!

### ISSUE THREAD

**Issue by wwmisswang** [pranayKD/faster_rcnn_colab_pytorch#1]
FileNotFoundError: [Errno 2] No such file or directory: 'drive/My Drive/saved_models/epoch_5.pt'

**Comment by pranayKD** [comment]
Hi, 

This is the weights file that I generated using the training data. Noticed a few bugs in this code which makes resume training cause spikes. I am working on fixing them. So, the code should be ready in a few days.

**Comment by pranayKD** [comment]
If you are planning to train the network from scratch on your training data then you can pass the file as empty string - `''`

`load_model = ''`

In case you want to continue training from saved checkpoint, you can use the file location where weights are stored in this. 

`load_model = 'file_location'`

But currently loading from saved checkpoint is broken. Fixing it

**Comment by pranayKD** [comment]
Loading from the saved checkpoint issue is fixed now. To train on images, provide the` load_model = ''`
